[2022-09-14T12:35:05.242+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Second_Dag.Random_Number_10_20 scheduled__2022-09-14T09:30:00+00:00 [queued]>
[2022-09-14T12:35:05.255+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Second_Dag.Random_Number_10_20 scheduled__2022-09-14T09:30:00+00:00 [queued]>
[2022-09-14T12:35:05.255+0300] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T12:35:05.256+0300] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-14T12:35:05.256+0300] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T12:35:05.272+0300] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Random_Number_10_20> on 2022-09-14 09:30:00+00:00
[2022-09-14T12:35:05.274+0300] {standard_task_runner.py:52} INFO - Started process 5776 to run task
[2022-09-14T12:35:05.276+0300] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Second_Dag', 'Random_Number_10_20', 'scheduled__2022-09-14T09:30:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/Second_Dag.py', '--cfg-path', '/tmp/tmp6yn58kf7', '--error-file', '/tmp/tmple1wmze_']
[2022-09-14T12:35:05.277+0300] {standard_task_runner.py:80} INFO - Job 43: Subtask Random_Number_10_20
[2022-09-14T12:35:05.317+0300] {task_command.py:371} INFO - Running <TaskInstance: Second_Dag.Random_Number_10_20 scheduled__2022-09-14T09:30:00+00:00 [running]> on host DESKTOP-6F0IB4Q.localdomain
[2022-09-14T12:35:05.367+0300] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Second_Dag
AIRFLOW_CTX_TASK_ID=Random_Number_10_20
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T09:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-14T09:30:00+00:00
[2022-09-14T12:35:05.368+0300] {logging_mixin.py:115} INFO - This is my random number between 10 and 20: 13
[2022-09-14T12:35:05.368+0300] {python.py:173} INFO - Done. Returned value was: None
[2022-09-14T12:35:05.372+0300] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=Second_Dag, task_id=Random_Number_10_20, execution_date=20220914T093000, start_date=20220914T093505, end_date=20220914T093505
[2022-09-14T12:35:05.408+0300] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-14T12:35:05.419+0300] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
