[2022-09-14T13:00:03.302+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Second_Dag.Random_Number_1_10 scheduled__2022-09-14T09:55:00+00:00 [queued]>
[2022-09-14T13:00:03.309+0300] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Second_Dag.Random_Number_1_10 scheduled__2022-09-14T09:55:00+00:00 [queued]>
[2022-09-14T13:00:03.309+0300] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:00:03.309+0300] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-14T13:00:03.309+0300] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-14T13:00:03.328+0300] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Random_Number_1_10> on 2022-09-14 09:55:00+00:00
[2022-09-14T13:00:03.330+0300] {standard_task_runner.py:52} INFO - Started process 9513 to run task
[2022-09-14T13:00:03.332+0300] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Second_Dag', 'Random_Number_1_10', 'scheduled__2022-09-14T09:55:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/Second_Dag.py', '--cfg-path', '/tmp/tmpgg4goqbz', '--error-file', '/tmp/tmpeh2nkyxs']
[2022-09-14T13:00:03.333+0300] {standard_task_runner.py:80} INFO - Job 57: Subtask Random_Number_1_10
[2022-09-14T13:00:03.373+0300] {task_command.py:371} INFO - Running <TaskInstance: Second_Dag.Random_Number_1_10 scheduled__2022-09-14T09:55:00+00:00 [running]> on host DESKTOP-6F0IB4Q.localdomain
[2022-09-14T13:00:03.427+0300] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Second_Dag
AIRFLOW_CTX_TASK_ID=Random_Number_1_10
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T09:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-14T09:55:00+00:00
[2022-09-14T13:00:03.428+0300] {logging_mixin.py:115} INFO - This is my random number between 1 and 10: 3
[2022-09-14T13:00:03.428+0300] {python.py:173} INFO - Done. Returned value was: None
[2022-09-14T13:00:03.432+0300] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=Second_Dag, task_id=Random_Number_1_10, execution_date=20220914T095500, start_date=20220914T100003, end_date=20220914T100003
[2022-09-14T13:00:03.464+0300] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-14T13:00:03.489+0300] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
